### ISSUE TITLE
subDomainsBrute为py2的等提供一个py3的版本吗

### ISSUE THREAD

**Issue by Coo1tige** [Cl0udG0d/HXnineTails#3]
subDomainsBrute为py2的等提供一个py3的版本吗

**Comment by Cl0udG0d** [comment]
subDomainsBrute源代码为：https://github.com/lijiejie/subDomainsBrute  
![image](https://user-images.githubusercontent.com/45556496/106239040-e9806e00-623c-11eb-9d6d-b473c6437c87.png)
最新源代码支持py3，只不过其releases版本中没有及时更新，你直接下载源代码：
>  git clone https://github.com/lijiejie/subDomainsBrute  

其项目就是支持py3的

**Comment by Coo1tige** [comment]
谢谢，解决了，我下的是Releases的版本。下源码就OK了。
