### ISSUE TITLE
路径报错

### ISSUE THREAD

**Issue by Coo1tige** [Cl0udG0d/HXnineTails#4]
![image](https://user-images.githubusercontent.com/40268914/106250075-1f7a1e00-624e-11eb-987f-34269cb5ef89.png)

**Comment by nvv5** [comment]
https://github.com/Cl0udG0d/HXnineTails/blob/8ebc8e2797633c69d9a4234b1d8bcbf868c89216/subDomainsBrute/subDomainsBruteMain.py#L16  
`{}{}`改成`{}\\{}`  好像就行了

**Comment by Cl0udG0d** [comment]
最新的更新中修改了该问题,本次更新中主要进行了:
+ `requirements.txt` 文件`aiodns`模块添加
+ `subDomainsBruteMain.py`文件中`saveFilePath`路径修改
+ `subDomainsBruteMain.py`文件中添加文件是否存在的判断  
下载最新版的源代码（注意不是releases）解决该issue中的问题
