### ISSUE TITLE
-s参数bug反馈

### ISSUE THREAD

**Issue by Hacker0x07** [Cl0udG0d/HXnineTails#7]
-s --attsrc 对SRC资产，进行信息搜集+crawlergo+xray , 例如 百度SRC python3 scan.py -s baidu.com

用-s参数挂在服务器上跑了几天，发现一个bug，虽然每次扫描完能收到推送，但是每次扫描完成如果有结果会自动替换上次上面完成的结果。
例如：www.xxx.com扫描完成且保存了xray扫描结果到saveXray文件夹下生成一个html文件，此时完成了一个子域名的扫描，例如：60d2f4fe0275d790764f40abc6734499.html

进行第二个子域名aaa.xxx.com扫描时，当这个子域名调用xray扫描完成且生成了结果后，会直接替换上次扫描完成的html文件，导致上一次扫描的结果直接消失，仅剩下本次扫描的结果，即：没有生成新的html文件，而是直接替换了原html文件的内容。也就是下图所示的内容（始终只有这一个html文件，并未生成新的扫描结果html文件）：
         
![bug](https://user-images.githubusercontent.com/68661583/106917121-eb699600-6742-11eb-86d8-c6e52e7c2564.png)

**Comment by Cl0udG0d** [comment]
已修复该bug，很抱歉让你几天的扫描结果消失了
