### ISSUE TITLE
扫描方式改为被动扫描是否可行

### ISSUE THREAD

**Issue by nannanshen** [Cl0udG0d/HXnineTails#9]
目前的逻辑是提取crawlergo爬取到的url让xray直接主动扫描，有些爬到的post包url直接扔去扫描效果并不好，没有参数。是否考虑使用crawlergo的--push-to-proxy参数直接把爬取结果推送到xray的被动扫描监听端口扫描完整的请求。自己试了一下是可以的，但程序不会自动退出，被动扫描的状态只能手动结束。并发通过调整xray的线程配置自己来做应该效果也不会太差。

**Comment by Cl0udG0d** [comment]
可以，下次更新的时候添加自主选择主动扫描还是被动扫描的选项配置

**Comment by nannanshen** [comment]
> 可以，下次更新的时候添加自主选择主动扫描还是被动扫描的选项配置

顺便再提两个建议：
1.给域名加http头的检测方式可以改进下，只判断404还是误报比较多。
2.建议将扫出来的子域名合并去重以后的集合和加上协议头的url集合分成两个文件保存，有些域名确实是能够解析但没有开放常见端口，用只加协议头去访问可能会直接过滤掉一些有用的子域名。
